List dataItems = [
  {
    "id": 1,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1799,
    "promotionPrice": 1799,
  },
  {
    "id": 2,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1799,
    "promotionPrice": 1899,
  },
  {
    "id": 3,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1899,
    "promotionPrice": 1899,
  },
  {
    "id": 4,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1999,
    "promotionPrice": 1999,
  },
  {
    "id": 5,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1599,
    "promotionPrice": 1599,
  },
  {
    "id": 6,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1599,
    "promotionPrice": 1599,
  },
  {
    "id": 7,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1799,
    "promotionPrice": 1799,
  },
  {
    "id": 8,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1799,
    "promotionPrice": 1899,
  },
  {
    "id": 9,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1899,
    "promotionPrice": 1899,
  },
  {
    "id": 10,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1999,
    "promotionPrice": 1999,
  },
  {
    "id": 11,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1599,
    "promotionPrice": 1599,
  },
  {
    "id": 12,
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": 1599,
    "promotionPrice": 1599,
  }
];
