List dataItems = [
  {
    "id": "1",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1799",
    "promotionPrice": "1799",
  },
  {
    "id": "2",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/b4.jpeg",
    "price": "1799",
    "promotionPrice": "1899",
  },
  {
    "id": "3",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/b5.png",
    "price": "1899",
    "promotionPrice": "1899",
  },
  {
    "id": "4",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/b3.jpg",
    "price": "1999",
    "promotionPrice": "1999",
  },
  {
    "id": "5",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/b6.png",
    "price": "1599",
    "promotionPrice": "1599",
  },
  {
    "id": "6",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat.png",
    "price": "1599",
    "promotionPrice": "1599",
  },
  {
    "id": "7",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/b7.png",
    "price": "1799",
    "promotionPrice": "1799",
  },
  {
    "id": "8",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1799",
    "promotionPrice": "1899",
  },
  {
    "id": "9",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat.png",
    "price": "1899",
    "promotionPrice": "1899",
  },
  {
    "id": "10",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/b4.jpeg",
    "price": "1999",
    "promotionPrice": "1999",
  },
  {
    "id": "11",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1599",
    "promotionPrice": "1599",
  },
  {
    "id": "12",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/b3.jpg",
    "price": "1599",
    "promotionPrice": "1599",
  }
];
