import 'package:flutter/material.dart';

List itemsTab = [
  {"icon": Icons.home, "size": 28.0},
  {"icon": Icons.shopping_cart, "size": 28.0},
  {"icon": Icons.person, "size": 28.0},
];
List dataItems = [
  {
    "id": "1",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1799",
    "promotionPrice": "1799",
  },
  {
    "id": "2",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1799",
    "promotionPrice": "1899",
  },
  {
    "id": "3",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat.png",
    "price": "1899",
    "promotionPrice": "1899",
  },
  {
    "id": "4",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1999",
    "promotionPrice": "1999",
  },
  {
    "id": "5",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1599",
    "promotionPrice": "1599",
  },
  {
    "id": "6",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat.png",
    "price": "1599",
    "promotionPrice": "1599",
  },
  {
    "id": "7",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1799",
    "promotionPrice": "1799",
  },
  {
    "id": "8",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1799",
    "promotionPrice": "1899",
  },
  {
    "id": "9",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat.png",
    "price": "1899",
    "promotionPrice": "1899",
  },
  {
    "id": "10",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1999",
    "promotionPrice": "1999",
  },
  {
    "id": "11",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1599",
    "promotionPrice": "1599",
  },
  {
    "id": "12",
    "name": "Boat Airdopes",
    "code": "Boat Airdopes",
    "img": "assets/images/boat1.jpeg",
    "price": "1599",
    "promotionPrice": "1599",
  }
];
